###
POST https://sprint3-edd5.onrender.com/articles
Content-Type: application/json

{
  "title": "게시글1",
  "content" : "첫번째로 쓴 게시글"

}

###
POST http://localhost:3000/articles
Content-Type: application/json

{
  "title": "게시글2",
  "content" : "두번째로 쓴 게시글"

}

###
GET http://localhost:3000/articles?&order=recent&search=게시글

###
GET http://localhost:3000/articles/eac70dc8-f7c7-4ee2-a14b-5ba43a1de989

###
PATCH http://localhost:3000/articles/34a7365a-a1d7-4072-a507-27f1e0a31703
Content-Type: application/json

{
  "title": "새로운 게시글"
}

###
DELETE http://localhost:3000/articles/34a7365a-a1d7-4072-a507-27f1e0a31703