###
POST http://localhost:3000/products/comments/b6f86b4f-981b-44f1-85c7-d56cb9cb2fe6
Content-Type: application/json

{
  "content" : "비싸네요"
}

###
GET http://localhost:3000/products/comments?cursor=7

###
GET http://localhost:3000/comments/products/d5726223-d3b0-4b20-b4a3-92107295a9fa
###
GET http://localhost:3000/articles/comments

###
POST http://localhost:3000/comments/articles/be7e73f7-751a-481f-98f0-5ed5131dba7d
Content-Type: application/json

{
  "content" : "비싸네요"
}

###
POST http://localhost:3000/comments/articles/be7e73f7-751a-481f-98f0-5ed5131dba7d
Content-Type: application/json

{
  "content" : "괜찮네요"
}

###
GET http://localhost:3000/comments/70359957-3d38-41d8-a051-fa449a5db755

###
PATCH http://localhost:3000/comments/70359957-3d38-41d8-a051-fa449a5db755
Content-Type: application/json

{
  "content" : "생각해보니 안 비싸네요"
}

### 
DELETE http://localhost:3000/comments/70359957-3d38-41d8-a051-fa449a5db755

